nao_dcm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Controllers ------------------------------------------------
  Head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HeadYaw
      - HeadPitch
    constraints:
      goal_time: 0.6
      HeadYaw: {trajectory: 0.5, goal: 0.1}
      HeadPitch: {trajectory: 0.5, goal: 0.1}
    gains:
      HeadYaw: {p: 1000, d: 1, i: 100, i_clamp: 1}
      HeadPitch: {p: 1000, d: 1, i: 100, i_clamp: 1}
    
  LeftArm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
    constraints:
      goal_time: 0.6
      LShoulderPitch: {trajectory: 0.5, goal: 0.1}
      LShoulderRoll: {trajectory: 0.5, goal: 0.1}
      LElbowYaw: {trajectory: 0.5, goal: 0.1}
      LElbowRoll: {trajectory: 0.5, goal: 0.6}
      LWristYaw: {trajectory: 0.5, goal: 0.1}
    gains:
      LShoulderPitch: {p: 80, d: 2, i: 4, i_clamp: 1}
      LShoulderRoll: {p: 50, d: 0.7, i: 5, i_clamp: 1}
      LElbowYaw: {p: 100, d: 0, i: 100, i_clamp: 1}
      LElbowRoll: {p: 100, d: 0, i: 100, i_clamp: 1}
      LWristYaw: {p: 100, d: 0, i: 100, i_clamp: 1}
   
      
  RightArm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
    constraints:
      goal_time: 0.6
      RShoulderPitch: {trajectory: 0.5, goal: 0.1}
      RShoulderRoll: {trajectory: 0.5, goal: 0.1}
      RElbowYaw: {trajectory: 0.5, goal: 0.1}
      RElbowRoll: {trajectory: 0.5, goal: 0.1}
      RWristYaw: {trajectory: 0.5, goal: 0.1}
    gains:
      RShoulderPitch: {p: 80, d: 2, i: 4, i_clamp: 1}
      RShoulderRoll: {p: 50, d: 0.7, i: 5, i_clamp: 1}
      RElbowYaw: {p: 100, d: 0, i: 100, i_clamp: 1}
      RElbowRoll: {p: 100, d: 0, i: 100, i_clamp: 1}
      RWristYaw: {p: 100, d: 0, i: 100, i_clamp: 1}
   
    
  LeftHand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - LHand
    constraints:
      goal_time: 0.6
      LHand: {trajectory: 0.5, goal: 0.1}
    gains:
      LHand: {p: 0, d: 0.1, i: 0, i_clamp: 1}
   
  RightHand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - RHand
    constraints:
      goal_time: 0.6
      RHand: {trajectory: 0.5, goal: 0.1}
    gains:
      RHand: {p: 0, d: 0.1, i: 0, i_clamp: 1}
 
  Pelvis_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHipYawPitch
    constraints:
      goal_time: 0.6
      LHipYawPitch: {trajectory: 0.5, goal: 0.1}
    gains:
      LHipYawPitch: {p: 100, d: 0, i: 1, i_clamp: 1}
      
  LeftLeg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
    constraints:
      goal_time: 0.6
      LHipRoll: {trajectory: 0.5, goal: 0.1}
      LHipPitch: {trajectory: 0.5, goal: 0.1}
      LKneePitch: {trajectory: 0.5, goal: 0.1}
    gains:
      LHipRoll: {p: 100, d: 0, i: 1, i_clamp: 1}
      LHipPitch: {p: 100, d: 0, i: 1 , i_clamp: 1}
      LKneePitch: {p: 100, d: 0, i: 1, i_clamp: 1}

  RightLeg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
    constraints:
      goal_time: 0.6
      RHipRoll: {trajectory: 0.5, goal: 0.1}
      RHipPitch: {trajectory: 0.5, goal: 0.1}
      RKneePitch: {trajectory: 0.5, goal: 0.1}
    gains:
      RHipRoll: {p: 100, d: 0, i: 1, i_clamp: 1}
      RHipPitch: {p: 100, d: 0, i: 1, i_clamp: 1}
      RKneePitch: {p: 100, d: 0, i: 1, i_clamp: 1}
  
  LeftFoot_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LAnklePitchJoint
      - LAnkleRoll
    constraints:
      goal_time: 0.6
      LAnklePitchJoint: {trajectory: 0.5, goal: 0.1}
      LAnkleRoll: {trajectory: 0.5, goal: 0.1}
    gains:
      LAnklePitchJoint: {p: 100, d: 0, i: 1, i_clamp: 1}
      LAnkleRoll: {p: 100, d: 0, i: 1, i_clamp: 1}

      
  RightFoot_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RAnklePitchJoint
      - RAnkleRoll
    constraints:
      goal_time: 0.6
      RAnklePitchJoint: {trajectory: 0.5, goal: 0.1}
      RAnkleRoll: {trajectory: 0.5, goal: 0.1}
    gains:
      RAnklePitchJoint: {p: 100, d: 0, i: 1, i_clamp: 1}
      RAnkleRoll: {p: 100, d: 0, i: 1, i_clamp: 1}
