controller_list:
  - name: fake_Head_controller
    type: $(arg fake_execution_type)
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_LArm_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - LHand
  - name: fake_RArm_controller
    type: $(arg fake_execution_type)
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
      - RHand
  - name: fake_LLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipYawPitch
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
  - name: fake_RLeg_controller
    type: $(arg fake_execution_type)
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
initial:  # Define initial robot poses per group
#  - group: Head
#    pose: home

  []