controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_left_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - LHipPitch
      - LKneePitch
      - LAnklePitchJoint
      - LAnkleRoll
  - name: fake_right_leg_controller
    type: $(arg fake_execution_type)
    joints:
      - RHipPitch
      - RKneePitch
      - RAnklePitchJoint
      - RAnkleRoll
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - LHand
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - RHand
  - name: fake_left_arm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: fake_right_arm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []